### ISSUE TITLE
Problem in IE and Firefox

### ISSUE THREAD

**Issue by creativefctr** [tgdev/animate-sass#12]
Hi,
There is a problem in your animation prefixer which causes most animations not to play in FF and IE.
It' adds quotes to the animation-name property like this: animation-name: 'zoomIn';
It works fine in webkit but in other browsers it causes a parse error. Here is the fix:
@mixin animate-prefixer($property, $value...) {
    -webkit-#{$property}:unquote($value);
       -moz-#{$property}:unquote($value);
         -o-#{$property}:unquote($value);
            #{$property}:unquote($value);
}
please update the master code.

**Comment by iamfredrik** [comment]
I can't get animate-sass to work in FF. Tried both v0.6.2 and v0.6.3. Both versions add quotes to the animation-name property.

**Comment by tgdev** [comment]
Hey,
What version of IE n FF?

Thanks,
Tom

**Comment by iamfredrik** [comment]
Latest version of FF, Windows and Mac. Didn't try IE. Chrome and Safari works.
