### ISSUE TITLE
gulp

### ISSUE THREAD

**Issue by fricks** [tgdev/animate-sass#15]
Hello im trying to use animate-sass in my project using gulp but the _animate.scss dont compile with my entire scripts in my css task. Any trick i have to do? Thank you

**Comment by fricks** [comment]
sorry, i figure out now how its works. i need edit the _settings.scss and choose which animations i want add. thanks for sass version :+1:

**Comment by tgdev** [comment]
No problem. Thanks for using it :-)

**Comment by mstnorris** [comment]
I can't get the modules to publish either. I have edited your settings file and tried using my own but that hasn't worked. There aren't any errors, it just isn't publishing.
