### ISSUE TITLE
Deprecation warnings with sass 3.4.11

### ISSUE THREAD

**Issue by jmcnevin** [tgdev/animate-sass#16]
I've started receiving many deprecation warnings similar to the following:

```
DEPRECATION WARNING: Passing (1s,), a non-string value, to unquote() will be an error in future versions of Sass.
DEPRECATION WARNING: Passing (fadeOutLeft,), a non-string value, to unquote() will be an error in future versions of Sass.
```

**Comment by tgdev** [comment]
Thanks for letting me know. This should just be a matter of taking those values within unquote() and wrapping them in single or double quotes so unquote knows it's a string.

Feel free to give this a go yourself and submit a pull request otherwise I can take a look at it.

Cheers,
Tom

**Comment by jmcnevin** [comment]
Would this be worth bumping the version number?
