### ISSUE TITLE
Remove -moz- and -o- vendor prefixes for keyframes

### ISSUE THREAD

**Issue by davidkpiano** [tgdev/animate-sass#18]
The only required prefix for the latest 2 versions of any modern browser are `-webkit`: http://caniuse.com/#feat=css-animation

Great job on this, by the way!

**Comment by tgdev** [comment]
Thanks David.

I'm slowly working on updating this repo to remove all the old prefixes as
well as add a few improvements so please keep following.

Thanks again,
Tom

**Comment by tgdev** [comment]
New patch version (v0.6.5) has removed all old vendor prefixes. Thanks @davidkpiano
