### ISSUE TITLE
Zoom effects do not work

### ISSUE THREAD

**Issue by cichy380** [tgdev/animate-sass#19]
Generated  <strong>animation-name</strong> has a zoom-effect name in quotes, and it is not work.

Sample of CSS code after I turned on <strong>ZoomIn</strong>:
<pre>
.zoomIn {
  -webkit-animation-name: "zoomIn";
  -o-animation-name: "zoomIn";
  animation-name: "zoomIn"; }
</pre>
and it should be without quotes:
<pre>
.zoomIn {
  -webkit-animation-name: zoomIn;
  -o-animation-name: zoomIn;
  animation-name: zoomIn; }
</pre>

I see that the bug is in <code>@include animate-prefixer(animation-name, $animate-name);</code>. You have to change it on <code>@include animate-prefixer(animation-name, #{$animate-name});</code>.

<hr>

I am using <strong>Firefox</strong> 39 / Windows 7.

**Comment by tgdev** [comment]
This should now be fixed by using the sass unquote function. Thanks @cichy380
