### ISSUE TITLE
Readme is inaccurate; instructions are confusing

### ISSUE THREAD

**Issue by bhagerty** [tgdev/animate-sass#22]
Your readme file says "There is a small section at the bottom of the _animate.scss file" etc., and lists out some code. 

First, this isn't true: there is no such code at the bottom of _animate.scss.

Second, this is baffling. I'm new to Sass, but I can't understand why there would be any reason to put this code into my main sass file. At most, I might put it in a separate sass file and import it into the main sass file. But why can't you just put this code in a module that's part of animate-sass?

**Comment by bhagerty** [comment]
In fact, it seems like your instructions might even be backwards.

My main.scss file loads all of my components.

If I load your README code before I load the main animate-sass file, _animate.sass, I get an error that the mixin "animate-prefixer" is undefined. 

This mixin is defined in _animate.sass (through import of your mixin file). So _animate.sass needs to be loaded before the code in the README that tries to use animate.prefixer. When I reordered my main.scss file to load _animate.sass first and your README code second, it compiled fine.

**Comment by tgdev** [comment]
Hi @bhagerty,

Thanks for your input. Regarding your initial issue, I had in fact moved the code snippet into it's own partial sass file (_base.scss) which is then imported into the main _animate.scss file but forgot to update the README to reflect those changes.

Could you please check to make sure you have the following imports in your animate.scss file.

@import "helpers/mixins",
	"helpers/settings",
	"helpers/base";

/* animation partials go here... */

**Comment by tgdev** [comment]
Just checked over the files and readme. There is in fact a _base.scss file located inside the helpers folder that . It gets imported into the main _animate.scss file of this repo.

The Readme instructs the reader of this under the Base Styles subheading below the Helpers heading.
