### ISSUE TITLE
Use @extend instead of variable configuration

### ISSUE THREAD

**Issue by romulof** [tgdev/animate-sass#31]
Instead of writing lots of configuration variables (that might be added and forgot to be removed as the project goes), why not define all animation classes using `%` selectors and `@extend` ?

Before:
```scss
$use-fadeIn: true;
@import 'animate-sass/animate';

.some-class {
...
}
```

After:
```scss
@import 'animate-sass/animate';

.some-class {
@extend %animate-fadeIn; // prefix with "animate" to prevent collision
...
}
```

This way only animations actually used will be outputted by sass compiler.

**Comment by tgdev** [comment]
Hey @romulof,

Thanks for the comment. I'm not a big fan of extend as it can muddle up the output if it's not used correctly. I'd possibly consider a bunch of mixins and then including those mixins in .some-class.

Here's a handy article I read on how mixins are actually more performant than extends (when gzipped)
https://csswizardry.com/2016/02/mixins-better-for-performance/
